#include "circuit_netlist.h"

#include <cmath>
#include <cstdio>
#include <sstream>

namespace {

const double kPi = 3.14159265358979323846;

// Земля в SPICE — всегда узел 0, как бы она ни звалась в графе.
std::string node(const CircuitGraph& g, int i) {
    return i == 0 ? std::string("0") : g.nodes[(size_t)i].name;
}

// Разность двух узлов без слагаемых-земли: "(V(a)-V(0))" читается хуже и лишний
// раз дразнит разборщики диалектов, а смысл тот же.
std::string ndiff(const CircuitGraph& g, int a, int b) {
    const bool ga = (a == 0), gb = (b == 0);
    if (ga && gb) return "0";
    if (gb) return "V(" + g.nodes[(size_t)a].name + ")";
    if (ga) return "(-V(" + g.nodes[(size_t)b].name + "))";
    return "(V(" + g.nodes[(size_t)a].name + ")-V(" + g.nodes[(size_t)b].name + "))";
}

std::string eng(double v) {
    char b[48];
    std::snprintf(b, sizeof(b), "%.10g", v);
    return b;
}

}  // namespace

std::string emit_spice_netlist(const CircuitGraph& g, const NetlistOptions& o) {
    std::ostringstream s;
    char buf[320];

    // Первая строка netlist'а в SPICE — всегда заголовок, её содержимое игнорируется.
    s << "* " << o.title << "\n";
    s << "*\n* Generated by U-CUDA from the system:\n";
    for (size_t i = 0; i < o.rhs_text.size(); ++i) {
        const std::string v = i < o.var_names.size() ? o.var_names[i] : std::to_string(i);
        s << "*   d" << v << "/dt = " << o.rhs_text[i] << "\n";
    }
    if (!o.scale.empty()) {
        s << "*\n* Amplitude scaling (system units per volt):\n";
        for (size_t i = 0; i < o.scale.size(); ++i) {
            const std::string v = i < o.var_names.size() ? o.var_names[i] : std::to_string(i);
            std::snprintf(buf, sizeof(buf), "*   %s = %.6g * V(n_%s)\n",
                          v.c_str(), o.scale[i], v.c_str());
            s << buf;
        }
    }
    if (g.time_scale > 0.0) {
        std::snprintf(buf, sizeof(buf),
            "*\n* Time scaling: 1/(R_unit*C) = %.6g 1/s, so one ODE time unit = %.6g s\n",
            g.time_scale, 1.0 / g.time_scale);
        s << buf;
    }
    s << "*\n* Op-amps and multipliers are emitted as EXPLICIT subcircuits rather than\n";
    s << "* vendor models on purpose: an external simulator then runs the same model\n";
    s << "* the U-CUDA solver runs, so any difference is a solver bug and not a model\n";
    s << "* mismatch. Swap in TL072 / AD633 subcircuits to compare against hardware.\n";
    s << "*\n";

    // --- модели ---------------------------------------------------------------
    if (o.opamp.ideal) {
        s << ".subckt uc_opamp inp inn out\n";
        s << "* Ideal op-amp: the solver treats it as a nullor (inputs equalised, output\n";
        s << "* sources any current). A VCVS with a large gain is the netlist equivalent.\n";
        s << "Eamp out 0 inp inn 1e6\n";
        s << ".ends uc_opamp\n\n";
    } else {
        const double gm = 2.0 * kPi * o.opamp.gbw_hz * o.opamp_cpole;
        const double rp = o.opamp.a0 / gm;
        std::snprintf(buf, sizeof(buf),
            ".param uc_gm=%s uc_rp=%s uc_cp=%s uc_vsat=%s\n",
            eng(gm).c_str(), eng(rp).c_str(), eng(o.opamp_cpole).c_str(),
            eng(o.opamp.vsat).c_str());
        s << buf;
        std::snprintf(buf, sizeof(buf),
            "* One-pole op-amp: A0 = %.6g, GBW = %.6g Hz, Vsat = %.6g V\n",
            o.opamp.a0, o.opamp.gbw_hz, o.opamp.vsat);
        s << buf;
        s << ".subckt uc_opamp inp inn out\n";
        s << "Gm  0 p inp inn {uc_gm}\n";
        s << "Rp  p 0 {uc_rp}\n";
        s << "Cp  p 0 {uc_cp}\n";
        s << "* Soft limiter, not a hard clip: a hard clip has zero derivative and Newton\n";
        s << "* stalls on it. The solver uses exactly this tanh.\n";
        s << "Bout out 0 V = {uc_vsat}*tanh(V(p)/{uc_vsat})\n";
        s << ".ends uc_opamp\n\n";
    }

    // --- пассив ----------------------------------------------------------------
    s << "* Resistors: value = R_unit / |monomial coefficient|\n";
    int ri = 0;
    for (const CircuitResistor& r : g.resistors) {
        ++ri;
        if (r.siemens == 0.0) {
            std::snprintf(buf, sizeof(buf), "* R%d %s %s open (coefficient is zero here)   ; %s\n",
                          ri, node(g, r.a).c_str(), node(g, r.b).c_str(), r.origin.c_str());
            s << buf;
            continue;
        }
        std::snprintf(buf, sizeof(buf), "R%-3d %-8s %-8s %-14s ; %s\n",
                      ri, node(g, r.a).c_str(), node(g, r.b).c_str(),
                      eng(r.ohm()).c_str(), r.origin.c_str());
        s << buf;
    }
    s << "\n";
    int ci = 0;
    for (const CircuitCapacitor& c : g.capacitors) {
        std::snprintf(buf, sizeof(buf), "C%-3d %-8s %-8s %s\n", ++ci,
                      node(g, c.a).c_str(), node(g, c.b).c_str(), eng(c.farad).c_str());
        s << buf;
    }
    s << "\n";

    int vi = 0;
    for (const CircuitVSource& v : g.vsources) {
        std::snprintf(buf, sizeof(buf), "V%-3d %-8s 0 DC %s\n", ++vi,
                      node(g, v.node).c_str(), eng(v.volt).c_str());
        s << buf;
    }
    if (!g.vsources.empty()) s << "\n";

    // --- активные -------------------------------------------------------------
    int xi = 0;
    for (const CircuitOpAmp& a : g.opamps) {
        std::snprintf(buf, sizeof(buf), "X%-3d %-8s %-8s %-8s uc_opamp\n", ++xi,
                      node(g, a.in_plus).c_str(), node(g, a.in_minus).c_str(),
                      node(g, a.out).c_str());
        s << buf;
    }
    s << "\n* Multipliers: AD633 transfer W = (X1-X2)(Y1-Y2)/10 + Z\n";
    int mi = 0;
    for (const CircuitMultiplier& m : g.multipliers) {
        const std::string zt = (m.z == 0) ? std::string()
                                          : " + V(" + g.nodes[(size_t)m.z].name + ")";
        std::snprintf(buf, sizeof(buf), "BM%-2d %-8s 0 V = %s*%s/10%s\n", ++mi,
                      node(g, m.out).c_str(),
                      ndiff(g, m.x1, m.x2).c_str(), ndiff(g, m.y1, m.y2).c_str(),
                      zt.c_str());
        s << buf;
    }

    // --- начальные условия и анализ ---------------------------------------------
    if (!o.x0_volts.empty() && !g.var_node.empty()) {
        s << "\n* Without a kick the circuit sits in a fixed point: chaos needs a start.\n.IC";
        for (size_t i = 0; i < o.x0_volts.size() && i < g.var_node.size(); ++i) {
            std::snprintf(buf, sizeof(buf), " V(%s)=%s",
                          node(g, g.var_node[i]).c_str(), eng(o.x0_volts[i]).c_str());
            s << buf;
        }
        s << "\n";
    }

    if (g.time_scale > 0.0) {
        const double t_end = o.t_end_ode / g.time_scale;
        const double h     = o.h_ode / g.time_scale;
        std::snprintf(buf, sizeof(buf),
            "\n* %.6g ODE time units. UIC honours the .IC line above.\n"
            ".TRAN %s %s 0 %s UIC\n",
            o.t_end_ode, eng(h).c_str(), eng(t_end).c_str(), eng(h).c_str());
        s << buf;
    }

    s << "\n.END\n";
    return s.str();
}
