#include "circuit_netlist.h"

#include <cmath>
#include <cstdio>
#include <sstream>
#include <string>

namespace {

const double kPi = 3.14159265358979323846;

// Земля в SPICE — всегда узел 0, как бы она ни звалась в графе.
//
// Индекс проверяется: эмиттер адресует g.nodes напрямую, и битый граф давал бы
// не диагностику, а нарушение прав доступа. Маркер в файле найти несравнимо легче.
std::string node(const CircuitGraph& g, int i) {
    if (i == 0) return "0";
    if (i < 0 || (size_t)i >= g.nodes.size()) return "BAD_NODE_" + std::to_string(i);
    return g.nodes[(size_t)i].name;
}

// Разность двух узлов без слагаемых-земли: "(V(a)-V(0))" читается хуже и лишний
// раз дразнит разборщики диалектов, а смысл тот же.
std::string ndiff(const CircuitGraph& g, int a, int b) {
    const bool ga = (a == 0), gb = (b == 0);
    if (ga && gb) return "0";
    if (gb) return "V(" + node(g, a) + ")";
    if (ga) return "(-V(" + node(g, b) + "))";
    return "(V(" + node(g, a) + ")-V(" + node(g, b) + "))";
}

std::string eng(double v) {
    char b[48];
    std::snprintf(b, sizeof(b), "%.10g", v);
    return b;
}

}  // namespace

std::string emit_spice_netlist(const CircuitGraph& g, const NetlistOptions& o) {
    std::ostringstream s;
    char buf[320];

    if (g.nodes.empty())
        return "* U-CUDA: the circuit graph is empty - nothing to export.\n"
               ".END\n";

    const bool poly = (o.dialect == NetlistDialect::Poly);

    // Первая строка netlist'а в SPICE — всегда заголовок, её содержимое игнорируется.
    s << "* " << o.title << "\n";
    s << "*\n* Generated by U-CUDA from the system:\n";
    for (size_t i = 0; i < o.rhs_text.size(); ++i) {
        const std::string v = i < o.var_names.size() ? o.var_names[i] : std::to_string(i);
        s << "*   d" << v << "/dt = " << o.rhs_text[i] << "\n";
    }
    if (!o.scale.empty()) {
        s << "*\n* Amplitude scaling (system units per volt):\n";
        for (size_t i = 0; i < o.scale.size(); ++i) {
            const std::string v = i < o.var_names.size() ? o.var_names[i] : std::to_string(i);
            std::snprintf(buf, sizeof(buf), "*   %s = %.6g * V(n_%s)\n",
                          v.c_str(), o.scale[i], v.c_str());
            s << buf;
        }
        s << "*\n* Probe the integrator outputs n_<var> and multiply by the factor above to\n";
        s << "* get system units. A phase portrait is one such output against another.\n";
    }
    if (g.time_scale > 0.0) {
        std::snprintf(buf, sizeof(buf),
            "*\n* Time scaling: 1/(R_unit*C) = %.6g 1/s, so one ODE time unit = %.6g s\n",
            g.time_scale, 1.0 / g.time_scale);
        s << buf;
    }
    s << "*\n* Dialect: " << (poly ? "SPICE 2 POLY sources (Multisim-friendly)"
                                   : "behavioural B sources (NGSpice, LTspice)") << "\n";
    s << "*\n* Op-amps and multipliers are emitted as EXPLICIT subcircuits rather than\n";
    s << "* vendor models on purpose: an external simulator then runs the same model\n";
    s << "* the U-CUDA solver runs, so any difference is a solver bug and not a model\n";
    s << "* mismatch. Swap in TL072 / AD633 to compare against hardware - those need\n";
    s << "* supply rails, which an ideal controlled source does not have, so there is\n";
    s << "* deliberately no power supply anywhere in this file.\n";
    s << "*\n";

    // --- модель ОУ ------------------------------------------------------------
    if (o.opamp.ideal) {
        s << ".subckt uc_opamp inp inn out\n";
        s << "* Ideal op-amp: the solver treats it as a nullor (inputs equalised, output\n";
        s << "* sources any current). A VCVS with a large gain is the netlist equivalent.\n";
        s << "Eamp out 0 inp inn 1e6\n";
        s << ".ends uc_opamp\n\n";
    } else {
        const double gm = 2.0 * kPi * o.opamp.gbw_hz * o.opamp_cpole;
        const double rp = o.opamp.a0 / gm;
        std::snprintf(buf, sizeof(buf),
            "* One-pole op-amp: A0 = %.6g, GBW = %.6g Hz, Vsat = %.6g V\n",
            o.opamp.a0, o.opamp.gbw_hz, o.opamp.vsat);
        s << buf;
        s << ".subckt uc_opamp inp inn out\n";
        // Числа печатаются прямо, без .param и фигурных скобок: их понимают не все.
        std::snprintf(buf, sizeof(buf), "Gm  0 p inp inn %s\n", eng(gm).c_str());    s << buf;
        std::snprintf(buf, sizeof(buf), "Rp  p 0 %s\n", eng(rp).c_str());            s << buf;
        std::snprintf(buf, sizeof(buf), "Cp  p 0 %s\n", eng(o.opamp_cpole).c_str()); s << buf;
        if (poly) {
            // tanh — поведенческое выражение, в этом диалекте его нет. Печатаем
            // ЛИНЕЙНЫЙ буфер и говорим об этом прямо: молча отдать схему без
            // ограничения хуже, чем отдать с предупреждением.
            s << "* WARNING: the soft limiter has no POLY equivalent, so this model keeps\n";
            s << "* the finite bandwidth but NOT the output saturation. For saturation use\n";
            s << "* a vendor op-amp model with supply rails.\n";
            s << "Ebuf out 0 p 0 1.0\n";
        } else {
            s << "* Soft limiter, not a hard clip: a hard clip has zero derivative and\n";
            s << "* Newton stalls on it. The solver uses exactly this tanh.\n";
            std::snprintf(buf, sizeof(buf), "Bout out 0 V = %s*tanh(V(p)/%s)\n",
                          eng(o.opamp.vsat).c_str(), eng(o.opamp.vsat).c_str());
            s << buf;
        }
        s << ".ends uc_opamp\n\n";
    }

    // --- пассив ----------------------------------------------------------------
    s << "* Resistors: value = R_unit / |monomial coefficient|\n";
    int ri = 0;
    for (const CircuitResistor& r : g.resistors) {
        ++ri;
        if (r.siemens == 0.0) {
            std::snprintf(buf, sizeof(buf), "* R%d %s %s open (coefficient is zero here)   ; %s\n",
                          ri, node(g, r.a).c_str(), node(g, r.b).c_str(), r.origin.c_str());
            s << buf;
            continue;
        }
        std::snprintf(buf, sizeof(buf), "R%-3d %-8s %-8s %-14s ; %s\n",
                      ri, node(g, r.a).c_str(), node(g, r.b).c_str(),
                      eng(r.ohm()).c_str(), r.origin.c_str());
        s << buf;
    }
    s << "\n";
    // Начальное условие ставится НА КОНДЕНСАТОР, а не только строкой .IC: директивы
    // анализа при импорте нередко отбрасываются, а свойство компонента переживает
    // дорогу. Без толчка схема стоит в нуле — начало координат у системы без
    // свободных членов является точным равновесием, и решатель из него не выйдет.
    int ci = 0;
    for (const CircuitCapacitor& c : g.capacitors) {
        ++ci;
        std::string ic;
        for (size_t v = 0; v < g.var_node.size() && v < o.x0_volts.size(); ++v) {
            if (c.b != g.var_node[v]) continue;
            // Напряжение НА конденсаторе: V(a) - V(b) = 0 - x0 при виртуальной земле.
            ic = " IC=" + eng(-o.x0_volts[v]);
            break;
        }
        std::snprintf(buf, sizeof(buf), "C%-3d %-8s %-8s %-10s%s\n", ci,
                      node(g, c.a).c_str(), node(g, c.b).c_str(),
                      eng(c.farad).c_str(), ic.c_str());
        s << buf;
    }
    s << "\n";

    int vi = 0;
    for (const CircuitVSource& v : g.vsources) {
        std::snprintf(buf, sizeof(buf), "V%-3d %-8s 0 DC %s\n", ++vi,
                      node(g, v.node).c_str(), eng(v.volt).c_str());
        s << buf;
    }
    if (!g.vsources.empty()) s << "\n";

    // --- активные -------------------------------------------------------------
    int xi = 0;
    for (const CircuitOpAmp& a : g.opamps) {
        std::snprintf(buf, sizeof(buf), "X%-3d %-8s %-8s %-8s uc_opamp\n", ++xi,
                      node(g, a.in_plus).c_str(), node(g, a.in_minus).c_str(),
                      node(g, a.out).c_str());
        s << buf;
    }

    s << "\n* Multipliers: AD633 transfer W = (X1-X2)(Y1-Y2)/10 + Z\n";
    int mi = 0;
    for (const CircuitMultiplier& m : g.multipliers) {
        ++mi;
        if (!poly) {
            const std::string zt = (m.z == 0) ? std::string() : " + V(" + node(g, m.z) + ")";
            std::snprintf(buf, sizeof(buf), "BM%-2d %-8s 0 V = %s*%s/10%s\n", mi,
                          node(g, m.out).c_str(),
                          ndiff(g, m.x1, m.x2).c_str(), ndiff(g, m.y1, m.y2).c_str(),
                          zt.c_str());
            s << buf;
            continue;
        }
        // POLY(2) раскладывается как c0, c1*v1, c2*v2, c3*v1^2, c4*v1*v2, c5*v2^2 —
        // нужен только c4 = 0.1. При ненулевом Z берём POLY(3), где порядок
        // c0, c1*v1, c2*v2, c3*v3, c4*v1^2, c5*v1*v2, то есть c3 = 1 и c5 = 0.1.
        if (m.z == 0) {
            std::snprintf(buf, sizeof(buf), "EM%-2d %-8s 0 POLY(2) %s %s %s %s 0 0 0 0 0.1\n",
                          mi, node(g, m.out).c_str(),
                          node(g, m.x1).c_str(), node(g, m.x2).c_str(),
                          node(g, m.y1).c_str(), node(g, m.y2).c_str());
        } else {
            // Три ПАРЫ узлов: у POLY(n) каждый вход задаётся парой, поэтому у Z
            // обязана быть своя опора. Коэффициенты: c3 = 1 даёт слагаемое Z,
            // c5 = 0.1 даёт произведение v1*v2.
            std::snprintf(buf, sizeof(buf),
                          "EM%-2d %-8s 0 POLY(3) %s %s %s %s %s 0 0 0 0 1 0 0.1\n",
                          mi, node(g, m.out).c_str(),
                          node(g, m.x1).c_str(), node(g, m.x2).c_str(),
                          node(g, m.y1).c_str(), node(g, m.y2).c_str(),
                          node(g, m.z).c_str());
        }
        s << buf;
    }

    // --- начальные условия и анализ ---------------------------------------------
    bool kick_hint = false;
    if (!o.x0_volts.empty() && !g.var_node.empty()) {
        s << "\n* The same start, as a directive. The origin is an exact equilibrium of this\n";
        s << "* circuit, so WITHOUT it every node stays at 0 V forever - that is not a bug\n";
        s << "* in the circuit but the absence of a kick.\n";
        s << "*\n";
        s << "* In Multisim the .IC line below is usually dropped on import. Set\n";
        s << "* Simulate -> Analyses and Simulation -> Transient -> Initial conditions to\n";
        s << "* \"User-defined\": it then uses the IC= values on the capacitors above.\n.IC";
        kick_hint = true;
        for (size_t i = 0; i < o.x0_volts.size() && i < g.var_node.size(); ++i) {
            std::snprintf(buf, sizeof(buf), " V(%s)=%s",
                          node(g, g.var_node[i]).c_str(), eng(o.x0_volts[i]).c_str());
            s << buf;
        }
        s << "\n";
    }

    // Запасной толчок на случай симулятора, который игнорирует и IC=, и .IC:
    // короткий импульс тока в суммирующий узел первого интегратора. Выводится
    // ЗАКОММЕНТИРОВАННЫМ, чтобы не менять схему у тех, у кого всё и так работает.
    if (kick_hint && !g.capacitors.empty()) {
        const int s_first = g.capacitors[0].a;   // суммирующий узел первого интегратора
        s << "\n* If the simulator ignores initial conditions altogether, uncomment these\n";
        s << "* two lines instead: a 10 us current pulse knocks the circuit off the origin.\n";
        std::snprintf(buf, sizeof(buf),
                      "* Vkick nkick 0 PULSE(0 1 0 1n 1n 10u 1)\n* Rkick nkick %s 3.3k\n",
                      node(g, s_first).c_str());
        s << buf;
    }

    if (g.time_scale > 0.0) {
        const double t_end = o.t_end_ode / g.time_scale;
        const double h     = o.h_ode / g.time_scale;
        std::snprintf(buf, sizeof(buf),
            "\n* %.6g ODE time units. UIC honours the .IC line above.\n"
            ".TRAN %s %s 0 %s UIC\n",
            o.t_end_ode, eng(h).c_str(), eng(t_end).c_str(), eng(h).c_str());
        s << buf;
    }

    s << "\n.END\n";
    return s.str();
}
